## A deeper look into Covid in Portugal

In this exercise notebook, you will be replicating what you just learned with another covid-related dataset, vaccinations.

### Initial Setup
Remember: 
Here we are importing libraries (code made by someone else) to agilize our exploration.

In [1]:
import pandas as pd #Pandas

First things first, we need to import the data from the github repository. They have several files, but for now we are only going to get **"vacinas.csv"**

With that said:
1. First read the csv (remember about the index and datetimes)
2. Take a quick look at the data
3. Do not forget to set the date as the index
4. Answer the following questions

In [2]:
data = 'https://raw.githubusercontent.com/dssg-pt/covid19pt-data/master/vacinas.csv' #This is the url of the file
df = #...
df

,data,doses,doses_novas,doses1,doses1_novas,doses2,doses2_novas,pessoas_vacinadas_completamente,pessoas_vacinadas_completamente_novas,pessoas_vacinadas_parcialmente,pessoas_vacinadas_parcialmente_novas
0,27-12-2020,4963.0,4963.0,4963.0,4963.0,0.0,0.0,0.0,0.0,4963.0,4963.0
1,28-12-2020,7754.0,2791.0,7754.0,2791.0,0.0,0.0,0.0,0.0,7754.0,2791.0
2,29-12-2020,20368.0,12614.0,20368.0,12614.0,0.0,0.0,0.0,0.0,20368.0,12614.0
3,30-12-2020,30543.0,10175.0,30543.0,10175.0,0.0,0.0,0.0,0.0,30543.0,10175.0
4,31-12-2020,32749.0,2206.0,32749.0,2206.0,0.0,0.0,0.0,0.0,32749.0,2206.0
...,...,...,...,...,...,...,...,...,...,...,...
168,13-06-2021,6545036.0,71023.0,4308544.0,65007.0,2236492.0,6016.0,2236492.0,6016.0,2072052.0,58991.0
169,14-06-2021,6572806.0,27770.0,4330244.0,21700.0,2242562.0,6070.0,2242562.0,6070.0,2087682.0,15630.0
170,15-06-2021,6665975.0,93169.0,4387691.0,57447.0,2278284.0,35722.0,2278284.0,35722.0,2109407.0,21725.0
171,16-06-2021,6768393.0,102418.0,4438408.0,50717.0,2329985.0,51701.0,2329985.0,51701.0,2108423.0,-984.0
172,17-06-2021,6879429.0,111036.0,4500125.0,61717.0,2379304.0,49319.0,2379304.0,49319.0,2120821.0,12398.0

Q1: What are the attributes (_columns_) of the data?

In [ ]:
##answer here

Q2: What are the top 5 days with most _doses1_novas_ ?  
_hint_  you can use [sort_values](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sort_values.html) function

,data,doses,doses_novas,doses1,doses1_novas,doses2,doses2_novas,pessoas_vacinadas_completamente,pessoas_vacinadas_completamente_novas,pessoas_vacinadas_parcialmente,pessoas_vacinadas_parcialmente_novas
112,18-04-2021,2520842.0,118818.0,1869400.0,113888.0,651442.0,4930.0,651442.0,4930.0,1217958.0,108958.0
166,11-06-2021,6417569.0,112389.0,4212783.0,74118.0,2204786.0,38271.0,2204786.0,38271.0,2007997.0,35847.0
125,01-05-2021,3252056.0,86303.0,2390948.0,69275.0,861108.0,17028.0,861108.0,17028.0,1529840.0,52247.0
133,09-05-2021,3845140.0,82485.0,2777561.0,68597.0,1067579.0,13888.0,1067579.0,13888.0,1709982.0,54709.0
89,26-03-2021,1505476.0,71432.0,1040109.0,66928.0,465367.0,4504.0,465367.0,4504.0,574742.0,62424.0

Q3: What is the day with most _doses2_novas_ ?  (Do not use sort_values function)

Q4: Select the days that had more doses2_novas than doses1_novas

Q5: If you were to show this data to the general population, how would you do it ? What graphs would you use ? 
Plot them, and lets discuss it! 

Remember! Be careful with your conclusions!
<img src="https://i.imgur.com/uCbnAaf.jpeg" alt="drawing" width="500"/>